name: CI Backend

on:
  pull_request:
    paths:
      - "**"
      - ".github/workflows/ci-backend.yml"
    types:
      - opened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v5

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
            .mypy_cache
            .pytest_cache
            .ruff_cache
          key: ${{ runner.os }}-tools-${{ hashFiles('uv.lock', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install system dependencies for PyAudio
        run: |
          sudo apt-get update
          sudo apt-get install -y portaudio19-dev

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff (format check)
        run: uv run ruff format --check .

      - name: Run Ruff (lint)
        run: uv run ruff check --output-format=github .

    #   - name: Run MyPy (type check)
    #     run: uv run mypy --config-file pyproject.toml .

    #   - name: Run tests
    #     run: uv run pytest tests
